const EErrors = {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    PET_ALREADY_EXISTS: 'PET_ALREADY_EXISTS',
    PET_NOT_FOUND: 'PET_NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED'
};

export default EErrors;